/*
 * This file is generated by jOOQ.
 */
package ru.bellintegrator.db;


import javax.annotation.Generated;

import ru.bellintegrator.db.tables.Books;


/**
 * Convenience access to all tables in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.books</code>.
     */
    public static final Books BOOKS = ru.bellintegrator.db.tables.Books.BOOKS;
}
